### ISSUE TITLE
Expose V's install dir and examples via ENV vars

### ISSUE THREAD

**Issue by larpon** [vlang/setup-v#2]
As the title states it would be nice to be able to get info about where these locations are from the shell.

For me it'd be nice to have them when testing `vab` against the official examples.

**Comment by ulises-jeremias** [comment]
@Larpon `setup-v` now has output! check the doc [here](https://github.com/marketplace/actions/setup-vlang)!

**Comment by larpon** [comment]
Perfect! Thanks @ulises-jeremias !
